### ISSUE TITLE
Data Access layer

### ISSUE THREAD

**Issue by domasmas** [domasmas/esf#5]
- Repositories for working with ES state
- Setup documents and related contracts
- Interfacing with MongoDB

work out what needs to go into the MongoDB configuration fiile
- database name in app.config?
- setup project configuration repository?
  - https://docs.mongodb.com/getting-started/shell/tutorial/install-mongodb-on-windows/#configure-a-windows-service-for-mongodb-community-edition
- creating indexes.

**Comment by vtrifonov-esfiddle** [comment]
Worth exploring for writing powershell scripts in Visual Studio:
https://visualstudiogallery.msdn.microsoft.com/c9eb3ba8-0c59-4944-9a62-6eee37294597

**Comment by vtrifonov-esfiddle** [comment]
Visual admin tool for MongoDB: https://robomongo.org/
